# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yUZV6p6PsdyeyjJXxchE3CO4fhcuhkVl
"""

import streamlit as st
import pandas as pd
import joblib


# ============================================================
# PAGE CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="Obesity Level Prediction",
    page_icon="📊",
    layout="centered"
)


# ============================================================
# LOAD TRAINED MODEL
# ============================================================

model = joblib.load("obesity_model.pkl")
scaler = joblib.load("scaler.pkl")
label_encoder = joblib.load("label_encoder.pkl")
feature_columns = joblib.load("feature_columns.pkl")


# ============================================================
# TITLE
# ============================================================

st.title("Obesity Level Prediction System")

st.write(
    """
    This application predicts a person's obesity level
    based on physical condition, eating habits and lifestyle.
    """
)


# ============================================================
# USER INPUT
# ============================================================

st.subheader("Enter Personal Information")


# ----------------------------
# Basic information
# ----------------------------

gender = st.selectbox(
    "Gender",
    ["Male", "Female"]
)

age = st.number_input(
    "Age",
    min_value=10.0,
    max_value=100.0,
    value=25.0
)

height = st.number_input(
    "Height (metres)",
    min_value=1.20,
    max_value=2.20,
    value=1.70,
    step=0.01
)

weight = st.number_input(
    "Weight (kg)",
    min_value=30.0,
    max_value=250.0,
    value=70.0,
    step=1.0
)


# ============================================================
# FAMILY HISTORY
# ============================================================

family_history = st.selectbox(
    "Family history of overweight?",
    ["yes", "no"]
)


# ============================================================
# HIGH CALORIE FOOD
# ============================================================

favc = st.selectbox(
    "Do you frequently consume high-calorie food?",
    ["yes", "no"]
)


# ============================================================
# VEGETABLE CONSUMPTION
# FCVC
# ============================================================

fcvc = st.slider(
    "Vegetable consumption frequency",
    min_value=1.0,
    max_value=3.0,
    value=2.0,
    step=0.1
)


# ============================================================
# NUMBER OF MAIN MEALS
# NCP
# ============================================================

ncp = st.slider(
    "Number of main meals per day",
    min_value=1.0,
    max_value=4.0,
    value=3.0,
    step=0.1
)


# ============================================================
# FOOD BETWEEN MEALS
# CAEC
# ============================================================

caec = st.selectbox(
    "Food consumption between meals",
    [
        "no",
        "Sometimes",
        "Frequently",
        "Always"
    ]
)


# ============================================================
# SMOKING
# ============================================================

smoke = st.selectbox(
    "Do you smoke?",
    ["yes", "no"]
)


# ============================================================
# WATER CONSUMPTION
# CH2O
# ============================================================

ch2o = st.slider(
    "Daily water consumption",
    min_value=1.0,
    max_value=3.0,
    value=2.0,
    step=0.1
)


# ============================================================
# CALORIE MONITORING
# SCC
# ============================================================

scc = st.selectbox(
    "Do you monitor your calorie consumption?",
    ["yes", "no"]
)


# ============================================================
# PHYSICAL ACTIVITY
# FAF
# ============================================================

faf = st.slider(
    "Physical activity frequency",
    min_value=0.0,
    max_value=3.0,
    value=1.0,
    step=0.1
)


# ============================================================
# TECHNOLOGY USE
# TUE
# ============================================================

tue = st.slider(
    "Time using technology devices",
    min_value=0.0,
    max_value=2.0,
    value=1.0,
    step=0.1
)


# ============================================================
# ALCOHOL CONSUMPTION
# CALC
# ============================================================

calc = st.selectbox(
    "Alcohol consumption",
    [
        "no",
        "Sometimes",
        "Frequently",
        "Always"
    ]
)


# ============================================================
# TRANSPORTATION
# MTRANS
# ============================================================

mtrans = st.selectbox(
    "Main transportation method",
    [
        "Automobile",
        "Bike",
        "Motorbike",
        "Public_Transportation",
        "Walking"
    ]
)


# ============================================================
# PREDICT BUTTON
# ============================================================

if st.button("Predict Obesity Level"):

    # ========================================================
    # CREATE INPUT DATAFRAME
    # ========================================================

    input_data = pd.DataFrame({
        "Gender": [gender],
        "Age": [age],
        "Height": [height],
        "Weight": [weight],
        "family_history_with_overweight": [family_history],
        "FAVC": [favc],
        "FCVC": [fcvc],
        "NCP": [ncp],
        "CAEC": [caec],
        "SMOKE": [smoke],
        "CH2O": [ch2o],
        "SCC": [scc],
        "FAF": [faf],
        "TUE": [tue],
        "CALC": [calc],
        "MTRANS": [mtrans]
    })


    # ========================================================
    # ONE-HOT ENCODING
    # ========================================================

    input_encoded = pd.get_dummies(
        input_data,
        drop_first=True
    )


    # ========================================================
    # MATCH TRAINING FEATURES
    # ========================================================

    input_encoded = input_encoded.reindex(
        columns=feature_columns,
        fill_value=0
    )


    # ========================================================
    # STANDARDIZATION
    # ========================================================

    input_scaled = scaler.transform(
        input_encoded
    )


    # ========================================================
    # MODEL PREDICTION
    # ========================================================

    prediction_numeric = model.predict(
        input_scaled
    )[0]


    # Convert numeric class back to original obesity name
    prediction_label = label_encoder.inverse_transform(
        [prediction_numeric]
    )[0]


    # ========================================================
    # DISPLAY RESULT
    # ========================================================

    st.success(
        f"Predicted Obesity Level: {prediction_label}"
    )


    st.subheader("Input Summary")

    st.dataframe(
        input_data,
        use_container_width=True
    )